# Generated by Django 5.0.3 on 2024-03-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shield', '0002_user_department_user_status_user_gander'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='is_superusers'),
        ),
    ]
