# Generated by Django 5.0.3 on 2024-03-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shield', '0003_user_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='DOB',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Status',
        ),
        migrations.AddField(
            model_name='user',
            name='last_update',
            field=models.DateField(blank=True, null=True, verbose_name='last_update'),
        ),
        migrations.AddField(
            model_name='user',
            name='phishing_awareness',
            field=models.CharField(blank=True, choices=[('aware', 'aware'), ('unaware', 'unaware')], max_length=15, null=True, verbose_name='Phishing Awareness'),
        ),
    ]
