# Generated by Django 5.0.3 on 2024-03-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shield', '0004_remove_user_dob_remove_user_status_user_last_update_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('url_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('description', models.CharField(max_length=150, verbose_name='Description')),
                ('type', models.CharField(choices=[('secure', 'secure'), ('unsecure', 'unsecure')], max_length=10, verbose_name='Type')),
            ],
        ),
    ]
