# Generated by Django 5.0.3 on 2024-03-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shield', '0005_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='description',
            field=models.CharField(max_length=150, unique=True, verbose_name='Description'),
        ),
    ]
