# Generated by Django 5.0.3 on 2024-03-19 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shield', '0006_alter_url_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phishing_awareness',
            field=models.CharField(choices=[('aware', 'aware'), ('unaware', 'unaware')], default='aware', max_length=15, verbose_name='Phishing Awareness'),
        ),
    ]
