# Generated by Django 5.0.3 on 2024-03-20 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shield', '0007_alter_user_phishing_awareness'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingPackage',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=150, unique=True, verbose_name='Description')),
                ('level', models.CharField(max_length=50, verbose_name='Level')),
                ('train_file', models.FileField(upload_to='uploads/', verbose_name='Training File')),
            ],
            options={
                'verbose_name': 'Training Package',
                'verbose_name_plural': 'Training Packages',
                'db_table': 'TrainingPackage',
            },
        ),
        migrations.AlterModelOptions(
            name='url',
            options={'verbose_name': 'Url', 'verbose_name_plural': 'Urls'},
        ),
        migrations.AlterModelTable(
            name='url',
            table='Url',
        ),
    ]
