# Generated by Django 5.0.3 on 2024-03-20 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shield', '0008_trainingpackage_alter_url_options_alter_url_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingpackage',
            name='train_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='Training File'),
        ),
    ]
