# Generated by Django 5.0.3 on 2024-03-24 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shield', '0009_alter_trainingpackage_train_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingpackage',
            name='level',
        ),
        migrations.AddField(
            model_name='trainingpackage',
            name='Name',
            field=models.CharField(default='1', max_length=150, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='trainingpackage',
            name='type',
            field=models.CharField(default=1, max_length=50, verbose_name='Type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trainingpackage',
            name='description',
            field=models.CharField(max_length=150, verbose_name='Description'),
        ),
    ]
