# Generated by Django 5.0.3 on 2024-03-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shield', '0010_remove_trainingpackage_level_trainingpackage_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentModel',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'department',
            },
        ),
        migrations.AlterField(
            model_name='trainingpackage',
            name='Name',
            field=models.CharField(default='1', max_length=150, unique=True, verbose_name='Name'),
        ),
    ]
