# Generated by Django 5.0.3 on 2024-03-24 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shield', '0011_departmentmodel_alter_trainingpackage_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Department',
        ),
    ]
