# Generated by Django 5.0.3 on 2024-03-24 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shield', '0012_remove_user_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shield.departmentmodel', verbose_name='Department'),
        ),
    ]
