# Generated by Django 5.0.3 on 2024-04-03 19:43

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shield', '0014_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendingURlsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=datetime.datetime(2024, 4, 3, 19, 43, 51, 287679, tzinfo=datetime.timezone.utc), verbose_name='Sending Time')),
                ('send_to', models.CharField(choices=[('user', 'user'), ('department', 'department')], max_length=10, verbose_name='Gander')),
                ('Department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shield.departmentmodel', verbose_name='Department')),
                ('URL_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shield.url', verbose_name='URl')),
                ('U_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'SendingURls',
                'verbose_name_plural': 'SendingURls',
                'db_table': 'SendingURls',
            },
        ),
        migrations.CreateModel(
            name='SurfingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shield.url', verbose_name='URl')),
                ('U_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Surfing',
                'verbose_name_plural': 'Surfing',
                'db_table': 'Surfing',
            },
        ),
    ]
