# Generated by Django 5.0.3 on 2024-04-04 19:51

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shield', '0015_sendingurlsmodel_surfingmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendingurlsmodel',
            name='Department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shield.departmentmodel', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='sendingurlsmodel',
            name='U_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='sendingurlsmodel',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 4, 19, 51, 20, 965780, tzinfo=datetime.timezone.utc), verbose_name='Sending Time'),
        ),
    ]
