# Generated by Django 5.0.3 on 2024-04-21 21:31

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shield', '0018_alter_sendingtrainingmodel_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendingtrainingmodel',
            name='email_text',
            field=models.CharField(max_length=100, null=True, verbose_name='email_text'),
        ),
        migrations.AddField(
            model_name='sendingurlsmodel',
            name='email_text',
            field=models.CharField(max_length=100, null=True, verbose_name='email_text'),
        ),
        migrations.AlterField(
            model_name='sendingtrainingmodel',
            name='Department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shield.departmentmodel', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='sendingtrainingmodel',
            name='Train_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shield.trainingpackage', verbose_name='Training Package'),
        ),
        migrations.AlterField(
            model_name='sendingtrainingmodel',
            name='U_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='sendingtrainingmodel',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 21, 21, 31, 42, 851394), verbose_name='Sending Time'),
        ),
        migrations.AlterField(
            model_name='sendingurlsmodel',
            name='Department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shield.departmentmodel', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='sendingurlsmodel',
            name='URL_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shield.url', verbose_name='URl'),
        ),
        migrations.AlterField(
            model_name='sendingurlsmodel',
            name='U_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='sendingurlsmodel',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 21, 21, 31, 42, 850395), verbose_name='Sending Time'),
        ),
        migrations.AlterField(
            model_name='surfingmodel',
            name='URL_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shield.url', verbose_name='URl'),
        ),
        migrations.AlterField(
            model_name='surfingmodel',
            name='U_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shield.departmentmodel', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last_update'),
        ),
    ]
