# Generated by Django 5.0.3 on 2024-04-26 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shield', '0019_sendingtrainingmodel_email_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='template',
            field=models.CharField(choices=[('fb', 'Facebook'), ('sbl', 'SPL'), ('unv', 'University')], max_length=10, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='sendingtrainingmodel',
            name='email_text',
            field=models.TextField(null=True, verbose_name='email_text'),
        ),
        migrations.AlterField(
            model_name='sendingtrainingmodel',
            name='send_to',
            field=models.CharField(choices=[('user', 'user'), ('department', 'department'), ('all_users', 'All users')], max_length=10, verbose_name='Send To'),
        ),
        migrations.AlterField(
            model_name='sendingtrainingmodel',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 16, 59, 37, 758624), verbose_name='Sending Time'),
        ),
        migrations.AlterField(
            model_name='sendingurlsmodel',
            name='email_text',
            field=models.TextField(null=True, verbose_name='email_text'),
        ),
        migrations.AlterField(
            model_name='sendingurlsmodel',
            name='send_to',
            field=models.CharField(choices=[('user', 'user'), ('department', 'department'), ('all_users', 'All users')], max_length=10, verbose_name='Send To'),
        ),
        migrations.AlterField(
            model_name='sendingurlsmodel',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 16, 59, 37, 757625), verbose_name='Sending Time'),
        ),
    ]
