# Generated by Django 5.0.3 on 2024-04-27 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shield', '0020_url_template_alter_sendingtrainingmodel_email_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendingtrainingmodel',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 27, 14, 35, 57, 707547), verbose_name='Sending Time'),
        ),
        migrations.AlterField(
            model_name='sendingurlsmodel',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 27, 14, 35, 57, 706547), verbose_name='Sending Time'),
        ),
        migrations.AlterField(
            model_name='url',
            name='template',
            field=models.CharField(choices=[('None', 'None'), ('fb', 'Facebook'), ('sbl', 'SPL'), ('unv', 'University')], max_length=10, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='Email address'),
        ),
    ]
