# Generated by Django 5.0.3 on 2024-04-27 18:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shield', '0021_alter_sendingtrainingmodel_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendingtrainingmodel',
            name='send_to',
            field=models.CharField(choices=[('user', 'user'), ('department', 'department'), ('all_users', 'All users')], max_length=15, verbose_name='Send To'),
        ),
        migrations.AlterField(
            model_name='sendingtrainingmodel',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 27, 18, 51, 3, 981543), verbose_name='Sending Time'),
        ),
        migrations.AlterField(
            model_name='sendingurlsmodel',
            name='send_to',
            field=models.CharField(choices=[('user', 'user'), ('department', 'department'), ('all_users', 'All users')], max_length=15, verbose_name='Send To'),
        ),
        migrations.AlterField(
            model_name='sendingurlsmodel',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 27, 18, 51, 3, 980543), verbose_name='Sending Time'),
        ),
        migrations.AlterField(
            model_name='url',
            name='template',
            field=models.CharField(choices=[('None', 'None'), ('fb', 'Facebook'), ('sbl', 'SPL'), ('unv', 'University')], max_length=15, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='url',
            name='type',
            field=models.CharField(choices=[('secure', 'secure'), ('unsecure', 'unsecure')], max_length=15, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gander',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=20, verbose_name='Gander'),
        ),
    ]
