# Generated by Django 5.0.3 on 2024-04-27 20:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shield', '0022_alter_sendingtrainingmodel_send_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendingtrainingmodel',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 27, 20, 59, 18, 345029), verbose_name='Sending Time'),
        ),
        migrations.AlterField(
            model_name='sendingurlsmodel',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 27, 20, 59, 18, 345029), verbose_name='Sending Time'),
        ),
    ]
