# Generated by Django 5.0.3 on 2024-05-21 09:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shield', '0024_alter_sendingtrainingmodel_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='m_name',
        ),
        migrations.AlterField(
            model_name='sendingtrainingmodel',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 21, 9, 58, 11, 526672), verbose_name='Sending Time'),
        ),
        migrations.AlterField(
            model_name='sendingurlsmodel',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 21, 9, 58, 11, 521101), verbose_name='Sending Time'),
        ),
        migrations.AlterField(
            model_name='user',
            name='f_name',
            field=models.CharField(max_length=150, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='l_name',
            field=models.CharField(max_length=150, verbose_name='Last name'),
        ),
    ]
